apiVersion: v1
kind: Pod
metadata:
  name: inspect-pvc
  namespace: vm
spec:
  containers:
  - name: inspector
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: os-pvc
      mountPath: /mnt/os-pvc
  restartPolicy: Never
  volumes:
  - name: os-pvc
    persistentVolumeClaim:
      claimName: os-pvc
