apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: os-pvc-runtime
  namespace: "{{ kubevirt_windows_namespace }}"
spec:
  source:
    pvc:
      name: os-pvc
      namespace: "{{ kubevirt_windows_namespace }}"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 60Gi
