---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: "os-dv"
spec:
  source:
    pvc:
      name: os-pvc
      namespace: "install-vm"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: {{ .Values.storage.osDiskSize }}
    storageClassName: {{ .Values.storageClassName }}
