apiVersion: v1
kind: Secret
metadata:
  name: "admin-password"
type: Opaque
stringData:
  # The key name "admin-password" becomes the filename inside the VM
  admin-password: {{ .Values.adminPassword | quote }}
