apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: "{{ .Release.Name }}-vm"
  labels:
    {{ .Values.vmLabels | toYaml | nindent 4 }}
spec:
  runStrategy: {{ .Values.runStrategy }}
  template:
    metadata:
      labels:
        {{.Values.vmLabels | toYaml | nindent 8 }}
    spec:
      domain:
        # Remove EFI firmware to use legacy BIOS (SeaBIOS)
        firmware: {}
        cpu:
          cores: {{ .Values.cpu.cores }}
        resources:
          requests:
            memory: "{{ .Values.memory }}"
        devices:
          disks:
            {{ .Values.disks | toYaml | nindent 12 }}

          interfaces:
            - name: default
              masquerade: {}
              model: virtio

      volumes:
        {{.Values.volumes | toYaml | nindent 8 }}

      networks:
        {{.Values.networks | toYaml | nindent 8 }}
