# Disks for installer VM
vmName: "windows-server-2022-installer"

disks:
  - name: windows-iso
    cdrom:
      bus: sata
    bootOrder: 1

  - name: virtio-drivers
    cdrom:
      bus: sata

  - name: unattend
    cdrom:
      bus: sata

  - name: os-disk
    disk:
      bus: virtio
    bootOrder: 2

# Volumes for installer VM
volumes:
  - name: os-disk
    persistentVolumeClaim:
      claimName: os-pvc

  - name: windows-iso
    dataVolume:
      name: windows-server-iso

  - name: virtio-drivers
    dataVolume:
      name: virtio-drivers

  - name: unattend
    dataVolume:
      name: unattend-iso

createInstallerDataVolumes: true
createOSPVC: true
