vmName: "windows-server-2022-runtime"

# Disks for runtime VM
disks:
  - name: os-disk
    disk:
      bus: virtio
    bootOrder: 1

# Volumes for runtime VM
volumes:
  - name: os-disk
    dataVolume:
      name: os-dv

createInstallerDataVolumes: false
createOSPVC: false
