vmName: "windows-server-2022-runtime"

# Disks for runtime VM
disks:
  - name: os-disk
    disk:
      bus: virtio
    bootOrder: 1

  # Unattended install ISO
  - name: specialise
    cdrom:
      bus: sata

# Volumes for runtime VM
volumes:
  - name: os-disk
    dataVolume:
      name: os-dv

  - name: specialise
    dataVolume:
      name: specialise-iso

createInstallerDataVolumes: false
createOSPVC: false
