# Minimum values.yaml for Windows Server KubeVirt VM

# VM configuration
vmName: "windows-server-2022"
runStrategy: Always

# Resources
cpu:
  cores: 2
memory: "4Gi"

# Storage
storageClassName: local-path
storage:
  osDiskSize: 60Gi
  isoSize: 10Gi
  virtioSize: 2Gi
  unattendSize: 10Mi

# VM Labels
vmLabels:
  kubevirt.io/size: small
  kubevirt.io/domain: testvm

# Network
networks:
  - name: default
    pod: {}

# Disks for runtime VM
disks:
  - name: os-disk
    disk:
      bus: virtio
    bootOrder: 1

  # Unattended install ISO
  - name: bootstrap
    cdrom:
      bus: sata

# Volumes for runtime VM
volumes:
  - name: os-disk
    dataVolume:
      name: os-dv

  - name: bootstrap
    dataVolume:
      name: bootstrap-iso
