- name: Create inspect PVC pod
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Pod
      metadata:
        name: inspect-pvc
        namespace: vm
      spec:
        containers:
          - name: inspector
            image: busybox
            command: ["sleep", "3600"]
            volumeMounts:
              - name: os-pvc
                mountPath: /mnt/os-pvc
        restartPolicy: Never
        volumes:
          - name: os-pvc
            persistentVolumeClaim:
              claimName: os-pvc

- name: Wait for inspect PVC pod to be ready
  kubernetes.core.k8s_info:
    kind: Pod
    name: inspect-pvc
    namespace: vm
  register: inspect_pod
  until: >
    inspect_pod.resources | length > 0 and
    inspect_pod.resources[0].status.phase == "Running"
  retries: 30
  delay: 5

- name: Copy disk.img from pod to local filesystem
  kubernetes.core.k8s_cp:
    namespace: vm
    pod: inspect-pvc
    remote_path: /mnt/os-pvc/disk.img
    local_path: "{{ role_path }}/files/isos/disk2.img"
    state: from_pod

- name: Remove inspect PVC pod
  kubernetes.core.k8s:
    api_version: v1
    kind: Pod
    name: inspect-pvc
    namespace: "{{ kubevirt_windows_namespace }}"
    state: absent
