---
# Create specliaise ISO
- name: Install pycdlib module
  ansible.builtin.pip:
    name: pycdlib

- name: Create bootstrap ISO for KubeVirt
  community.general.iso_create:
    src_files:
      - "{{ role_path }}/files/bootstrap/bootstrap.ps1"
    dest_iso: "{{ role_path }}/files/isos/bootstrap.iso"
    interchange_level: 3
    joliet: 3
    vol_ident: AUTOUNATTEND
    rock_ridge: "1.09"

- name: Install Kubernetes Python module
  ansible.builtin.pip:
    name: kubernetes

- name: Create VM namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ kubevirt_windows_namespace }}"
    state: present

- name: Check if Python HTTP server is running on port 8000
  ansible.builtin.command: lsof -i :8000
  register: kubevirt_windows_http_server_check
  ignore_errors: true
  changed_when: false

- name: Start Python HTTP server to serve ISOs if not running
  ansible.builtin.shell: >
    nohup python3 -m http.server 8000 > /tmp/isos-http.log 2>&1 &
  args:
    chdir: "{{ role_path }}/files/isos"
  async: 1000
  poll: 0
  when: kubevirt_windows_http_server_check.rc != 0
  changed_when: kubevirt_windows_http_server_check.rc != 0

- name: Pick the first 192.* IP address
  ansible.builtin.set_fact:
    kubevirt_windows_localhost_ip: "{{ ansible_all_ipv4_addresses | select('match', '^192\\.') | list | first }}"

# -----------------------------
# Installer VM
# -----------------------------
- name: Include secrets variables
  ansible.builtin.include_vars:
    file: "{{ role_path }}/secrets.enc.yaml"

- name: Deploy Windows VM
  kubernetes.core.helm:
    name: "{{ kubevirt_windows_vm_name }}"
    chart_ref: "{{ role_path }}/../../helm"
    namespace: "{{ kubevirt_windows_namespace }}"
    values_files:
      - "{{ role_path }}/../../helm/values.yaml"
    values:
      runStrategy: Once
      diskImageURL: "http://{{ kubevirt_windows_localhost_ip }}:8000/golden.img"
      bootstrapURL: "http://{{ kubevirt_windows_localhost_ip }}:8000/bootstrap.iso"
      adminPassword: "{{ vault_admin_password }}"

- name: Wait for the VM to enter Succeeded phase
  vars:
    vmi_name: "{{ kubevirt_windows_vm_name }}"
  until: kubevirt_windows_vmi_status.resources[0].status.phase == "Succeeded"
  retries: 60
  delay: 30
  kubernetes.core.k8s_info:
    api_version: kubevirt.io/v1
    kind: VirtualMachineInstance
    name: "{{ kubevirt_windows_vm_name }}"
    namespace: "{{ kubevirt_windows_namespace }}"
  register: kubevirt_windows_vmi_status

- name: Remove secret volume from VM spec after bootstrap
  kubernetes.core.k8s_json_patch:
    kind: VirtualMachine
    name: "{{ kubevirt_windows_vm_name }}"
    namespace: "{{ kubevirt_windows_namespace }}"
    patch:
      # Remove the bootstrap ISO disk
      - op: remove
        path: /spec/template/spec/domain/devices/disks/1
      - op: remove
        path: /spec/template/spec/volumes/1
      # Remove the secret disk
      - op: remove
        path: /spec/template/spec/domain/devices/disks/2
      - op: remove
        path: /spec/template/spec/volumes/2
      # Set the VM to always run, this also restarts it
      - op: replace
        path: /spec/runStrategy
        value: "Always"
